### ISSUE TITLE
More automated cell creation

### ISSUE THREAD

**Issue by reed-foster** [qnngroup/qnngds#68]
I wonder if it makes sense to redesign `cells.py` so that there's one general method which takes in a die_parameters instance and a curried function for generating the device. For example, if you have a device method `ntron(choke_w, channel_w, ...)`, you could define `my_ntron = lambda: ntron(my_choke_w, my_channel_w, ...)` and then pass `my_ntron` as an argument to some more generic cell-creation method.

If all the methods in `cells.py` are similar (e.g. instantiate the device and add some pads), then this might reduce the amount of code someone has to write to contribute a new cell, but if you think it's important to have customization in these methods, then definitely keep things the way they are. Minor customization could be achieved when defining the curried device-creation function, but if you need to add a lot of stuff, then it kind of defeats the point.

**Comment by emmakbat** [comment]
Having begun to use this library, I think this is a good idea, and even more importantly such a refactoring could also be done in such a way to decrease redundancy in the Design() class. The Design() class contains a lot of functions which are basically wrappers on the cell functions, which is yet another layer of code a contributor must write to add a new cell. I'd be happy to work on this, but I think I would need to have some discussion with others first on what this should look like.

**Comment by emmakbat** [comment]
I've been reflecting on this more and drafting a potential generic cell function. Since I made the 4-pt nanowire cell and the hTron cell, I've gotten a better idea of what customizations are necessary, and it's mostly the pad placement. It can be easily programmatically determined how many pads any given device needs, but not how they should be laid out (N/S/E/W) or which pads should be routed to which device ports. If we can design an interface that makes it easy for the user to specify pad placement, I think we can unify cell creation into a single function.

Perhaps we could do something like an Enum class that lets the user select "nTron," "nanowire," etc (or making the devices classes with a Type that can be detected) and then the otherwise-generic cell function has programmed into it the correct pad placement for a given type of device. This would still greatly decrease the amount of code required to integrate a new device into the system, to just setting a few variable values within the generic cell function.

**Comment by emmakbat** [comment]
I think the minimum required customizable values would be 1) cell_scaling_factor (maybe both x and y) to change the default minimum device size as needed 2) number of pads for N, W, S, E (each separately specified), 3) list of which ports should go straight to ground, 4) dictionary mapping device ports (keys) to tuples specifying the pattern for pad ports 

This is probably more than we'd want to have the user manually specify each time, but little enough that it would be much easier for a developer to figure out appropriate values here rather than writing a new cells function each time. I'm not 100% sure the best way to design the interface, but I have a prototype that works for both hTrons and nanowires right now
